export const CHECK_MOBILE = 'CHECK_MOBILE';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_HIDE_SECSIDEBAR = 'SET_HIDE_SECSIDEBAR';
export const SET_SHOW_SECSIDEBAR = 'SET_SHOW_SECSIDEBAR';
export const SET_CURRENT_URL = 'SET_CURRENT_URL';
